import { FruitConfig, FruitType } from '../types';

export const FRUIT_CONFIGS: Record<FruitType, FruitConfig> = {
  apple: {
    type: 'apple',
    name: 'Apple',
    radius: 42,
    points: 10,
    isRare: false,
    gravity: 920,
    juiceColor: '#ef4444',
    secondaryJuiceColor: '#fca5a5',
    fleshColor: '#fef9c3',
    skinColor: '#dc2626',
  },
  watermelon: {
    type: 'watermelon',
    name: 'Watermelon',
    radius: 56,
    points: 10,
    isRare: false,
    gravity: 960,
    juiceColor: '#f43f5e',
    secondaryJuiceColor: '#fda4af',
    fleshColor: '#e11d48',
    skinColor: '#166534',
  },
  orange: {
    type: 'orange',
    name: 'Orange',
    radius: 44,
    points: 10,
    isRare: false,
    gravity: 930,
    juiceColor: '#f97316',
    secondaryJuiceColor: '#ffedd5',
    fleshColor: '#fb923c',
    skinColor: '#ea580c',
  },
  banana: {
    type: 'banana',
    name: 'Banana',
    radius: 46,
    points: 10,
    isRare: false,
    gravity: 880,
    juiceColor: '#facc15',
    secondaryJuiceColor: '#fef9c3',
    fleshColor: '#fefce8',
    skinColor: '#ca8a04',
  },
  pineapple: {
    type: 'pineapple',
    name: 'Pineapple',
    radius: 58,
    points: 20,
    isRare: true,
    gravity: 1000,
    juiceColor: '#eab308',
    secondaryJuiceColor: '#fef08a',
    fleshColor: '#fde047',
    skinColor: '#854d0e',
  },
  strawberry: {
    type: 'strawberry',
    name: 'Strawberry',
    radius: 36,
    points: 10,
    isRare: false,
    gravity: 890,
    juiceColor: '#e11d48',
    secondaryJuiceColor: '#fecdd3',
    fleshColor: '#fb7185',
    skinColor: '#be123c',
  },
  mango: {
    type: 'mango',
    name: 'Mango',
    radius: 48,
    points: 20,
    isRare: true,
    gravity: 940,
    juiceColor: '#f59e0b',
    secondaryJuiceColor: '#fde68a',
    fleshColor: '#fbbf24',
    skinColor: '#d97706',
  },
  kiwi: {
    type: 'kiwi',
    name: 'Kiwi',
    radius: 40,
    points: 15,
    isRare: false,
    gravity: 910,
    juiceColor: '#84cc16',
    secondaryJuiceColor: '#d9f99d',
    fleshColor: '#65a30d',
    skinColor: '#78350f',
  },
};

export const FRUIT_TYPES = Object.keys(FRUIT_CONFIGS) as FruitType[];
